# Production values for csv-processor
# Override values for production EKS deployment with IRSA

replicaCount: 2  # Start with 2 replicas for HA

image:
  repository: oguzhanbolukbas/cloud-native-csv-processor
  tag: latest
  pullPolicy: Always  # Use Always for latest tag in production

# Service Account for IRSA
serviceAccount:
  create: false  # Will be created by deployment script with proper annotations
  name: csv-processor-sa

service:
  type: ClusterIP
  port: 3000
  nginx_port: 80

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 15m
    memory: 64Mi

# Production environment
env:
  NODE_ENV: production

# Remove secrets section - using IRSA instead
# AWS credentials will be provided via IAM roles

configmap:
  name: app-config
  tier: backend
  AWS_REGION: eu-north-1
  S3_BUCKET_NAME: cloud-native-csv-processor-uploads-business-case
  DOCKER_IMAGE_NAME: oguzhanbolukbas/cloud-native-csv-processor
  DOCKER_IMAGE_TAG: latest

# Nginx deployment values - Free Tier optimized
nginx:
  replicaCount: 1  # Single nginx instance for Free Tier
  image:
    repository: nginx
    tag: "1.25-alpine"  # Use specific version for production
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 320Mi   # Increased to prevent OOMKilled
    requests:
      cpu: 5m
      memory: 16Mi
  
  hpa:
    minReplicas: 1    # Start with 1 for Free Tier
    maxReplicas: 3    # Max 3 for Free Tier limits
    targetCPUUtilizationPercentage: 50  # Higher threshold to prevent frequent scaling
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes for stability
      percentPolicy:
        value: 25  # Conservative scale-down
        periodSeconds: 60
      podsPolicy:
        value: 1  # Remove 1 pod at a time
        periodSeconds: 60
      selectPolicy: "Min"  # Conservative approach
    scaleUp:
      stabilizationWindowSeconds: 60   # 1 minute delay
      percentPolicy:
        value: 50  # 50% increase max
        periodSeconds: 30
      podsPolicy:
        value: 1  # Add 1 pod at a time
        periodSeconds: 30
      selectPolicy: "Min"  # Conservative approach

# API HPA values - Free Tier optimized
hpa:
  minReplicas: 1      # Start with 1 for Free Tier
  maxReplicas: 3      # Max 3 for Free Tier limits
  targetCPUUtilizationPercentage: 50  # Higher threshold to prevent frequent scaling
  scaleDown:
    stabilizationWindowSeconds: 300  # 5 minutes for stability
    percentPolicy:
      value: 25  # Conservative scale-down
      periodSeconds: 60
    podsPolicy:
      value: 1  # Remove 1 pod at a time
      periodSeconds: 60
    selectPolicy: "Min"  # Conservative approach
  scaleUp:
    stabilizationWindowSeconds: 60   # 1 minute delay
    percentPolicy:
      value: 50  # 50% increase max
      periodSeconds: 30
    podsPolicy:
      value: 1  # Add 1 pod at a time
      periodSeconds: 30
    selectPolicy: "Min"  # Conservative approach

# Storage configuration
storageClass:
  name: gp2  # Use gp2 for EKS

pvc:
  name: shared-static-pvc
  accessMode: ReadWriteOnce
  size: 1Gi  # Reduced to 1GB for Free Tier

# Node selection and tolerations
nodeSelector: {}  # Remove specific node selector for Free Tier flexibility

tolerations: []

# Remove pod anti-affinity for Free Tier (single node cluster)
affinity: {}

# Ingress configuration for AWS ALB
ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/tags: Environment=production,Project=csv-processor
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
  hosts:
    - host: ""  # No specific host, will accept all
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false  # App needs to write to uploads directory
  capabilities:
    drop:
    - ALL

# Probes for production
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
