apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: nginx-app
    tier: backend
data:
  AWS_REGION: eu-north-1
  S3_BUCKET_NAME: cloud-native-csv-processor-uploads-business-case
  DOCKER_IMAGE_NAME: oguzhanbolukbas/cloud-native-csv-processor
  DOCKER_IMAGE_TAG: latest
