apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTJNTlZNQ0pMS041V01QR0o=        # base64 encoded
  AWS_SECRET_ACCESS_KEY: K0JFdTNHVS9XZG40RkQwQkhFbU04cDhZOGppSjY2T2c5ZTBkQ1hXYQ==
  DOCKERHUB_USERNAME: b2d1emhhbmJvbHVrYmFz
  DOCKERHUB_PASSWORD: ZGNrcl9wYXRfd0pYcHpkOE85QkliamFId0ZDR2FtQjV2MFdB
