apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name | default "app-config" }}
  labels:
    app: {{ .Values.appLabel | default "nginx-app" }}
    tier: {{ .Values.configmap.tier | default "backend" }}
data:
  AWS_REGION: {{ .Values.configmap.AWS_REGION | quote }}
  S3_BUCKET_NAME: {{ .Values.configmap.S3_BUCKET_NAME | quote }}
  DOCKER_IMAGE_NAME: {{ .Values.configmap.DOCKER_IMAGE_NAME | quote }}
  DOCKER_IMAGE_TAG: {{ .Values.configmap.DOCKER_IMAGE_TAG | quote }}
