apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csv-processor.fullname" . }}-nginx
  labels:
    {{- include "csv-processor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "csv-processor.fullname" . }}-nginx
  template:
    metadata:
      labels:
        app: {{ include "csv-processor.fullname" . }}-nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-files
              mountPath: /usr/share/nginx/html/static
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: shared-static-pvc
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
      {{- with .Values.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
