apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "csv-processor.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "csv-processor.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.scaleDown.stabilizationWindowSeconds | default 120 }}
      policies:
      - type: Percent
        value: {{ .Values.hpa.scaleDown.percentPolicy.value | default 50 }}
        periodSeconds: {{ .Values.hpa.scaleDown.percentPolicy.periodSeconds | default 60 }}
      - type: Pods
        value: {{ .Values.hpa.scaleDown.podsPolicy.value | default 2 }}
        periodSeconds: {{ .Values.hpa.scaleDown.podsPolicy.periodSeconds | default 60 }}
      selectPolicy: {{ .Values.hpa.scaleDown.selectPolicy | default "Max" }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.scaleUp.stabilizationWindowSeconds | default 0 }}
      policies:
      - type: Percent
        value: {{ .Values.hpa.scaleUp.percentPolicy.value | default 100 }}
        periodSeconds: {{ .Values.hpa.scaleUp.percentPolicy.periodSeconds | default 15 }}
      - type: Pods
        value: {{ .Values.hpa.scaleUp.podsPolicy.value | default 4 }}
        periodSeconds: {{ .Values.hpa.scaleUp.podsPolicy.periodSeconds | default 15 }}
      selectPolicy: {{ .Values.hpa.scaleUp.selectPolicy | default "Max" }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
