apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "csv-processor.fullname" . }}-nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "csv-processor.fullname" . }}-nginx
  minReplicas: {{ .Values.nginx.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.nginx.hpa.maxReplicas | default 5 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.nginx.hpa.targetCPUUtilizationPercentage | default 50 }}
