apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: {{ include "csv-processor.fullname" . }}-nginx
data:
  nginx.conf: |
    server {
        listen 80;

        client_body_buffer_size     32k;
        client_header_buffer_size   8k;
        large_client_header_buffers 8 64k;

        location /static/ {
            alias /usr/share/nginx/html/static/;
            try_files $uri $uri/ =404;
        }

        location / {
            proxy_pass http://{{ include "csv-processor.fullname" . }}:{{ .Values.service.port }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
