apiVersion: v1
kind: Secret
metadata:
  name: {{ include "csv-processor.fullname" . }}-aws-credentials
  labels:
    {{- include "csv-processor.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_SECRET_ACCESS_KEY }}
