apiVersion: v1
kind: Service
metadata:
  name: {{ include "csv-processor.fullname" . }}-nginx
  labels:
    {{- include "csv-processor.nginx.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "csv-processor.nginx.selectorLabels" . | nindent 4 }}
